
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://ptfront.netlify.app/api/*"
  to = "http://pthome.herokuapp.com/api/*"
  status = 200
  force = true 
  
